---
  - name: Main playbook
    hosts: servers
    become: True
    
    roles:

#      - install_prometheus
#      - install_alert_manager 
#      - install_node_exporter
      - config_prometheus 
      - install_grafana

